"""Initial migration

Revision ID: 91fb7373e449
Revises: 
Create Date: 2026-04-08 20:15:48.991369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91fb7373e449'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuraciones_clan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clan_id', sa.Integer(), nullable=True),
    sa.Column('tolerancia_entrada_min', sa.Integer(), nullable=True),
    sa.Column('tolerancia_retardo_leve', sa.Integer(), nullable=True),
    sa.Column('tolerancia_retardo_grave', sa.Integer(), nullable=True),
    sa.Column('tolerancia_salida_min', sa.Integer(), nullable=True),
    sa.Column('break1_inicio', sa.Time(), nullable=False),
    sa.Column('break1_fin', sa.Time(), nullable=False),
    sa.Column('break1_tolerancia', sa.Integer(), nullable=True),
    sa.Column('break2_inicio', sa.Time(), nullable=False),
    sa.Column('break2_fin', sa.Time(), nullable=False),
    sa.Column('break2_tolerancia', sa.Integer(), nullable=True),
    sa.Column('fuga_minutos_limite', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clan_id'], ['clanes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clan_id')
    )
    op.create_index(op.f('ix_configuraciones_clan_id'), 'configuraciones_clan', ['id'], unique=False)
    op.create_table('resumenes_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coder_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('estado_entrada', sa.String(length=50), nullable=True),
    sa.Column('minutos_retardo', sa.Integer(), nullable=True),
    sa.Column('estado_salida', sa.String(length=50), nullable=True),
    sa.Column('salida_inferida', sa.Boolean(), nullable=True),
    sa.Column('tiempo_trabajado_min', sa.Integer(), nullable=True),
    sa.Column('ausente', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['coder_id'], ['coder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumenes_diarios_id'), 'resumenes_diarios', ['id'], unique=False)
    op.create_table('incidencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resumen_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('minutos', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resumen_id'], ['resumenes_diarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidencias_id'), 'incidencias', ['id'], unique=False)
    op.drop_table('_prisma_migrations')
    op.alter_column('clanes', 'hora_entrada',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('clanes', 'hora_salida',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('clanes', 'tiempo_alimentacion_minutos',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('clanes_nombre_key'), table_name='clanes')
    op.create_index(op.f('ix_clanes_id'), 'clanes', ['id'], unique=False)
    op.create_unique_constraint(None, 'clanes', ['nombre'])
    op.alter_column('coder', 'moodle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('coder', 'clan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('coder_cedula_key'), table_name='coder')
    op.drop_index(op.f('coder_moodle_id_key'), table_name='coder')
    op.create_index(op.f('ix_coder_id'), 'coder', ['id'], unique=False)
    op.create_unique_constraint(None, 'coder', ['cedula'])
    op.create_unique_constraint(None, 'coder', ['moodle_id'])
    op.drop_constraint(op.f('coder_clan_id_fkey'), 'coder', type_='foreignkey')
    op.create_foreign_key(None, 'coder', 'clanes', ['clan_id'], ['id'])
    op.alter_column('correos_enviados', 'coder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('correos_enviados', 'tipo_correo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'ausencia'::character varying"))
    op.alter_column('correos_enviados', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('correos_enviados', 'fecha_envio',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_correos_enviados_id'), 'correos_enviados', ['id'], unique=False)
    op.drop_constraint(op.f('correos_enviados_coder_id_fkey'), 'correos_enviados', type_='foreignkey')
    op.create_foreign_key(None, 'correos_enviados', 'coder', ['coder_id'], ['id'])
    op.add_column('registros', sa.Column('tipo_evento', sa.String(length=30), nullable=True))
    op.add_column('registros', sa.Column('dispositivo', sa.String(length=50), nullable=True))
    op.alter_column('registros', 'coder_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('registros', 'fecha',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('registros', 'hora',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('registros', 'estado_acceso',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_registros_id'), 'registros', ['id'], unique=False)
    op.drop_constraint(op.f('registros_coder_id_fkey'), 'registros', type_='foreignkey')
    op.create_foreign_key(None, 'registros', 'coder', ['coder_id'], ['id'])
    op.alter_column('team_leaders', 'clan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('team_leaders_correo_key'), table_name='team_leaders')
    op.create_index(op.f('ix_team_leaders_id'), 'team_leaders', ['id'], unique=False)
    op.create_unique_constraint(None, 'team_leaders', ['correo'])
    op.drop_constraint(op.f('team_leaders_clan_id_fkey'), 'team_leaders', type_='foreignkey')
    op.create_foreign_key(None, 'team_leaders', 'clanes', ['clan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'team_leaders', type_='foreignkey')
    op.create_foreign_key(op.f('team_leaders_clan_id_fkey'), 'team_leaders', 'clanes', ['clan_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'team_leaders', type_='unique')
    op.drop_index(op.f('ix_team_leaders_id'), table_name='team_leaders')
    op.create_index(op.f('team_leaders_correo_key'), 'team_leaders', ['correo'], unique=True)
    op.alter_column('team_leaders', 'clan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'registros', type_='foreignkey')
    op.create_foreign_key(op.f('registros_coder_id_fkey'), 'registros', 'coder', ['coder_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_registros_id'), table_name='registros')
    op.alter_column('registros', 'estado_acceso',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('registros', 'hora',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('registros', 'fecha',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('registros', 'coder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('registros', 'dispositivo')
    op.drop_column('registros', 'tipo_evento')
    op.drop_constraint(None, 'correos_enviados', type_='foreignkey')
    op.create_foreign_key(op.f('correos_enviados_coder_id_fkey'), 'correos_enviados', 'coder', ['coder_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_index(op.f('ix_correos_enviados_id'), table_name='correos_enviados')
    op.alter_column('correos_enviados', 'fecha_envio',
               existing_type=postgresql.TIMESTAMP(precision=3),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('correos_enviados', 'estado',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('correos_enviados', 'tipo_correo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'ausencia'::character varying"))
    op.alter_column('correos_enviados', 'coder_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'coder', type_='foreignkey')
    op.create_foreign_key(op.f('coder_clan_id_fkey'), 'coder', 'clanes', ['clan_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
    op.drop_constraint(None, 'coder', type_='unique')
    op.drop_constraint(None, 'coder', type_='unique')
    op.drop_index(op.f('ix_coder_id'), table_name='coder')
    op.create_index(op.f('coder_moodle_id_key'), 'coder', ['moodle_id'], unique=True)
    op.create_index(op.f('coder_cedula_key'), 'coder', ['cedula'], unique=True)
    op.alter_column('coder', 'clan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('coder', 'moodle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'clanes', type_='unique')
    op.drop_index(op.f('ix_clanes_id'), table_name='clanes')
    op.create_index(op.f('clanes_nombre_key'), 'clanes', ['nombre'], unique=True)
    op.alter_column('clanes', 'tiempo_alimentacion_minutos',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clanes', 'hora_salida',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('clanes', 'hora_entrada',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.create_table('_prisma_migrations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('migration_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('logs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rolled_back_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('applied_steps_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('_prisma_migrations_pkey'))
    )
    op.drop_index(op.f('ix_incidencias_id'), table_name='incidencias')
    op.drop_table('incidencias')
    op.drop_index(op.f('ix_resumenes_diarios_id'), table_name='resumenes_diarios')
    op.drop_table('resumenes_diarios')
    op.drop_index(op.f('ix_configuraciones_clan_id'), table_name='configuraciones_clan')
    op.drop_table('configuraciones_clan')
    # ### end Alembic commands ###
